### ISSUE TITLE
argumentError (wrong number of arguments (given 3, expected 2)):

### ISSUE THREAD

**Issue by bhavinatharva** [YuKitAs/rails-rest-api#25]
Processing by AuthenticationController#login as */*
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)

  
ArgumentError (wrong number of arguments (given 3, expected 2)):
  
app/authentications/authenticate_user.rb:4:in `initialize'
app/controllers/authentication_controller.rb:6:in `login'

**Comment by YuKitAs** [comment]
Hi, thanks for reporting the issue. It was due to a breaking change introduced in the newer version of [simple_command](https://rubygems.org/gems/simple_command/versions/0.0.9?locale=de). The tests only work with simple_command <= 0.1.0. I locked the version in 5381e4c4ce230ef2c8e306c745ae2512f58c24ee.
